repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.1
    hooks:
      - id: check-github-workflows
  - repo: local
    hooks:
      # Running common tools though pixi so that they are in sync with the ones used
      # by our editors (and does not duplicate downloads).

      # Formatters
      - id: pixi-format-cargo
        name: "Run cargo format through pixi"
        entry: pixi run fmt-cargo --
        language: system
        types_or: [rust]
      - id: pixi-format-air
        name: "Run air format through pixi"
        entry: pixi run fmt-air
        language: system
        types_or: [r]
        pass_filenames: false
      - id: pixi-format-tombi
        name: "Run tombi format through pixi"
        entry: pixi run fmt-tombi --stdin-filename
        language: system
        types: [toml]
        exclude: Cargo\.lock

      # Linters
      - id: pixi-check-cargo
        name: "Run cargo check through pixi"
        entry: pixi run check-cargo
        language: system
        types_or: [rust]
        pass_filenames: false
      - id: pixi-check-clippy
        name: "Run clippy through pixi"
        entry: pixi run check-clippy --allow-dirty
        language: system
        types_or: [rust]
        pass_filenames: false
      - id: pixi-check-typos
        name: "Run typos through pixi"
        entry: pixi run check-typos
        language: system
