[workspace]
name = "yr"
description = "y-crdt bindings to R lang"
authors = ["AntoinePrv <AntoinePrv@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["osx-64", "osx-arm64", "linux-64", "linux-aarch64"]

[environments]
dev = { features = ["build", "test", "check", "dev"], solve-group = "default" }

# Building the R extension package

[feature.build.dependencies]
sccache = ">=0.8.1"
c-compiler = ">=1.7.0,<2"
rust = ">=1.85.0"
# R library and headers needed at compile time
r-base = "*"
# R tools needed to generate NAMESPACE
r-roxygen2 = "*"

[feature.build.activation.env]
RUSTC_WRAPPER = "sccache"

[feature.build.target.osx.activation.env]
RUSTFLAGS = "-C link-arg=-rpath -C link-arg=$CONDA_PREFIX/lib/"

[feature.build.target.linux.activation.env]
RUSTFLAGS = "-C link-arg=-Wl,-rpath,$CONDA_PREFIX/lib/R/lib"

[feature.build.tasks.build-lib]
description = "Compile Rust code into a library"
# Set target dir so that it does not conflict with the one from R
cmd = """
cargo build \
    --manifest-path=src/rust/Cargo.toml \
    --target-dir=$PIXI_PROJECT_ROOT/target/build \
    --lib
"""
inputs = ["src/rust/src/**/*.rs", "src/rust/Cargo.*"]
outputs = ["target/build/**/*"]

[feature.build.tasks.build-wrappers]
description = "Generate R/extendr-wrappers.R from Rust #[extendr] macros"
cmd = """
cargo --locked run \
    --manifest-path=rust/Cargo.toml \
    --target-dir=$PIXI_PROJECT_ROOT/target/build \
    --bin document \
"""
cwd = "src"
inputs = ["src/rust/src/**/*.rs", "src/rust/Cargo.toml"]
outputs = ["R/extendr-wrappers.R"]

[feature.build.tasks.build-namespace]
description = "Generate R documentation and NAMESPACE from roxygen2 comments"
cmd = """
Rscript -e 'roxygen2::roxygenise(load = "source")'
"""
depends-on = ["build-wrappers"]
inputs = ["R/*.R", "DESCRIPTION"]
outputs = ["man/*.Rd", "NAMESPACE"]

# Running R import tests

[feature.test.dependencies]
r-devtools = "*"

[feature.test.tasks.test-r]
description = "Run R bindings tests"
cmd = "Rscript -e 'devtools::test()'"
env = { DEBUG = "1" }
depends-on = ["build-namespace"]

[feature.test.tasks.test-cargo]
description = "Run Rust unit tests"
cmd = """
cargo --locked test \
    --manifest-path=src/rust/Cargo.toml \
    --target-dir=$PIXI_PROJECT_ROOT/target/build \
    --workspace \
"""

# Code quality checks

[feature.check.dependencies]
pre-commit = ">=3.7.1"
tombi = ">=0.9.2"
air = ">=0.8.2"
typos = "*"

[feature.check.tasks]
# Formatters
fmt-cargo = "cargo fmt --manifest-path=src/rust/Cargo.toml"
fmt-air = "air format R/ tests/ tools/"
fmt-tombi = "tombi format"
fmt = { depends-on = ["fmt-cargo", "fmt-air", "fmt-tombi"] }
# Checkers
check-typos = "typos --write-changes"
check = { depends-on = ["check-cargo", "check-clippy", "check-typos"] }
# Pre-commit easy alias
pre-commit = "pre-commit"
pre-commit-all = "pre-commit run --all-files"
# Alias for what is being run in ci (pre-commit runs checks and formatter)
ci = { depends-on = ["pre-commit-all"] }

[feature.check.tasks.check-cargo]
cmd = """
cargo --locked check \
    --manifest-path=src/rust/Cargo.toml \
    --target-dir=$PIXI_PROJECT_ROOT/target/check \
    --all-targets \
    --workspace \
"""
env.RUSTFLAGS = "-Dwarnings"

[feature.check.tasks.check-clippy]
# --fix flag causes pixi to not return an error, failing pre-commit
cmd = """cargo --locked clippy --manifest-path=src/rust/Cargo.toml"""
env.RUSTFLAGS = "-Dwarnings"
env.CARGO_TARGET_DIR = "$PIXI_PROJECT_ROOT/target/clippy"

[feature.dev.dependencies]
rust-src = ">=1.79.0"
