# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib yar, .registration = TRUE
NULL

Transaction <- new.env(parent = emptyenv())

Transaction$lock <- function(doc, mutable = FALSE, origin = NULL) .Call(wrap__Transaction__lock, doc, mutable, origin)

Transaction$origin <- function() .Call(wrap__Transaction__origin, self)

Transaction$commit <- function() .Call(wrap__Transaction__commit, self)

Transaction$unlock <- function() .Call(wrap__Transaction__unlock, self)

Transaction$state_vector <- function() .Call(wrap__Transaction__state_vector, self)

Transaction$encode_diff_v1 <- function(state_vector) .Call(wrap__Transaction__encode_diff_v1, self, state_vector)

Transaction$encode_diff_v2 <- function(state_vector) .Call(wrap__Transaction__encode_diff_v2, self, state_vector)

Transaction$encode_state_as_update_v1 <- function(state_vector) .Call(wrap__Transaction__encode_state_as_update_v1, self, state_vector)

Transaction$encode_state_as_update_v2 <- function(state_vector) .Call(wrap__Transaction__encode_state_as_update_v2, self, state_vector)

Transaction$apply_update_v1 <- function(data) .Call(wrap__Transaction__apply_update_v1, self, data)

Transaction$apply_update_v2 <- function(data) .Call(wrap__Transaction__apply_update_v2, self, data)

Transaction$snapshot <- function() .Call(wrap__Transaction__snapshot, self)

#' @export
`$.Transaction` <- function (self, name) { func <- Transaction[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Transaction` <- `$.Transaction`

Origin <- new.env(parent = emptyenv())

Origin$new <- function(data) .Call(wrap__Origin__new, data)

Origin$equal <- function(other) .Call(wrap__Origin__equal, self, other)

Origin$not_equal <- function(other) .Call(wrap__Origin__not_equal, self, other)

Origin$less_than <- function(other) .Call(wrap__Origin__less_than, self, other)

Origin$less_than_equal <- function(other) .Call(wrap__Origin__less_than_equal, self, other)

Origin$greater_than <- function(other) .Call(wrap__Origin__greater_than, self, other)

Origin$greater_than_equal <- function(other) .Call(wrap__Origin__greater_than_equal, self, other)

Origin$to_string <- function() .Call(wrap__Origin__to_string, self)

Origin$to_bytes <- function() .Call(wrap__Origin__to_bytes, self)

Origin$to_hex <- function() .Call(wrap__Origin__to_hex, self)

#' @export
`$.Origin` <- function (self, name) { func <- Origin[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Origin` <- `$.Origin`

ArrayRef <- new.env(parent = emptyenv())

ArrayRef$len <- function(transaction) .Call(wrap__ArrayRef__len, self, transaction)

ArrayRef$insert_any <- function(transaction, index, obj) .Call(wrap__ArrayRef__insert_any, self, transaction, index, obj)

ArrayRef$insert_text <- function(transaction, index) .Call(wrap__ArrayRef__insert_text, self, transaction, index)

ArrayRef$insert_array <- function(transaction, index) .Call(wrap__ArrayRef__insert_array, self, transaction, index)

ArrayRef$insert_map <- function(transaction, index) .Call(wrap__ArrayRef__insert_map, self, transaction, index)

ArrayRef$get <- function(transaction, index) .Call(wrap__ArrayRef__get, self, transaction, index)

ArrayRef$remove <- function(transaction, index) .Call(wrap__ArrayRef__remove, self, transaction, index)

ArrayRef$observe <- function(f, key) .Call(wrap__ArrayRef__observe, self, f, key)

ArrayRef$unobserve <- function(key) .Call(wrap__ArrayRef__unobserve, self, key)

#' @export
`$.ArrayRef` <- function (self, name) { func <- ArrayRef[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ArrayRef` <- `$.ArrayRef`

ArrayEvent <- new.env(parent = emptyenv())

ArrayEvent$target <- function() .Call(wrap__ArrayEvent__target, self)

ArrayEvent$delta <- function(transaction) .Call(wrap__ArrayEvent__delta, self, transaction)

ArrayEvent$path <- function() .Call(wrap__ArrayEvent__path, self)

ArrayEvent$inserts <- function(transaction) .Call(wrap__ArrayEvent__inserts, self, transaction)

ArrayEvent$removes <- function(transaction) .Call(wrap__ArrayEvent__removes, self, transaction)

#' @export
`$.ArrayEvent` <- function (self, name) { func <- ArrayEvent[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ArrayEvent` <- `$.ArrayEvent`

MapRef <- new.env(parent = emptyenv())

MapRef$len <- function(transaction) .Call(wrap__MapRef__len, self, transaction)

MapRef$contains_key <- function(transaction, key) .Call(wrap__MapRef__contains_key, self, transaction, key)

MapRef$insert_any <- function(transaction, key, obj) .Call(wrap__MapRef__insert_any, self, transaction, key, obj)

MapRef$insert_text <- function(transaction, key) .Call(wrap__MapRef__insert_text, self, transaction, key)

MapRef$insert_array <- function(transaction, key) .Call(wrap__MapRef__insert_array, self, transaction, key)

MapRef$insert_map <- function(transaction, key) .Call(wrap__MapRef__insert_map, self, transaction, key)

MapRef$get <- function(transaction, key) .Call(wrap__MapRef__get, self, transaction, key)

MapRef$keys <- function(transaction) .Call(wrap__MapRef__keys, self, transaction)

MapRef$items <- function(transaction) .Call(wrap__MapRef__items, self, transaction)

MapRef$remove <- function(transaction, key) .Call(wrap__MapRef__remove, self, transaction, key)

MapRef$clear <- function(transaction) .Call(wrap__MapRef__clear, self, transaction)

MapRef$observe <- function(f, key) .Call(wrap__MapRef__observe, self, f, key)

MapRef$unobserve <- function(key) .Call(wrap__MapRef__unobserve, self, key)

#' @export
`$.MapRef` <- function (self, name) { func <- MapRef[[name]]; environment(func) <- environment(); func }

#' @export
`[[.MapRef` <- `$.MapRef`

MapEvent <- new.env(parent = emptyenv())

MapEvent$target <- function() .Call(wrap__MapEvent__target, self)

MapEvent$keys <- function(transaction) .Call(wrap__MapEvent__keys, self, transaction)

MapEvent$path <- function() .Call(wrap__MapEvent__path, self)

#' @export
`$.MapEvent` <- function (self, name) { func <- MapEvent[[name]]; environment(func) <- environment(); func }

#' @export
`[[.MapEvent` <- `$.MapEvent`

SyncMessage <- new.env(parent = emptyenv())

SyncMessage$decode_v1 <- function(data) .Call(wrap__SyncMessage__decode_v1, data)

SyncMessage$decode_v2 <- function(data) .Call(wrap__SyncMessage__decode_v2, data)

SyncMessage$new <- function(sync_step1 = NULL, sync_step2 = NULL, update = NULL) .Call(wrap__SyncMessage__new, sync_step1, sync_step2, update)

SyncMessage$from_sync_step1 <- function(state_vector) .Call(wrap__SyncMessage__from_sync_step1, state_vector)

SyncMessage$from_sync_step2 <- function(data) .Call(wrap__SyncMessage__from_sync_step2, data)

SyncMessage$from_update <- function(data) .Call(wrap__SyncMessage__from_update, data)

SyncMessage$equal <- function(other) .Call(wrap__SyncMessage__equal, self, other)

SyncMessage$not_equal <- function(other) .Call(wrap__SyncMessage__not_equal, self, other)

SyncMessage$encode_v1 <- function() .Call(wrap__SyncMessage__encode_v1, self)

SyncMessage$encode_v2 <- function() .Call(wrap__SyncMessage__encode_v2, self)

SyncMessage$step <- function() .Call(wrap__SyncMessage__step, self)

SyncMessage$is_sync_step1 <- function() .Call(wrap__SyncMessage__is_sync_step1, self)

SyncMessage$is_sync_step2 <- function() .Call(wrap__SyncMessage__is_sync_step2, self)

SyncMessage$is_update <- function() .Call(wrap__SyncMessage__is_update, self)

SyncMessage$state_vector <- function() .Call(wrap__SyncMessage__state_vector, self)

SyncMessage$data <- function() .Call(wrap__SyncMessage__data, self)

#' @export
`$.SyncMessage` <- function (self, name) { func <- SyncMessage[[name]]; environment(func) <- environment(); func }

#' @export
`[[.SyncMessage` <- `$.SyncMessage`

StateVector <- new.env(parent = emptyenv())

StateVector$decode_v1 <- function(data) .Call(wrap__StateVector__decode_v1, data)

StateVector$decode_v2 <- function(data) .Call(wrap__StateVector__decode_v2, data)

StateVector$is_empty <- function() .Call(wrap__StateVector__is_empty, self)

StateVector$len <- function() .Call(wrap__StateVector__len, self)

StateVector$contains_client <- function(client_id) .Call(wrap__StateVector__contains_client, self, client_id)

StateVector$equal <- function(other) .Call(wrap__StateVector__equal, self, other)

StateVector$not_equal <- function(other) .Call(wrap__StateVector__not_equal, self, other)

StateVector$less_than <- function(other) .Call(wrap__StateVector__less_than, self, other)

StateVector$less_than_equal <- function(other) .Call(wrap__StateVector__less_than_equal, self, other)

StateVector$greater_than <- function(other) .Call(wrap__StateVector__greater_than, self, other)

StateVector$greater_than_equal <- function(other) .Call(wrap__StateVector__greater_than_equal, self, other)

StateVector$encode_v1 <- function() .Call(wrap__StateVector__encode_v1, self)

StateVector$encode_v2 <- function() .Call(wrap__StateVector__encode_v2, self)

#' @export
`$.StateVector` <- function (self, name) { func <- StateVector[[name]]; environment(func) <- environment(); func }

#' @export
`[[.StateVector` <- `$.StateVector`

DeleteSet <- new.env(parent = emptyenv())

DeleteSet$decode_v1 <- function(data) .Call(wrap__DeleteSet__decode_v1, data)

DeleteSet$decode_v2 <- function(data) .Call(wrap__DeleteSet__decode_v2, data)

DeleteSet$new <- function() .Call(wrap__DeleteSet__new)

DeleteSet$is_empty <- function() .Call(wrap__DeleteSet__is_empty, self)

DeleteSet$len <- function() .Call(wrap__DeleteSet__len, self)

DeleteSet$is_deleted <- function(id) .Call(wrap__DeleteSet__is_deleted, self, id)

DeleteSet$equal <- function(other) .Call(wrap__DeleteSet__equal, self, other)

DeleteSet$not_equal <- function(other) .Call(wrap__DeleteSet__not_equal, self, other)

DeleteSet$encode_v1 <- function() .Call(wrap__DeleteSet__encode_v1, self)

DeleteSet$encode_v2 <- function() .Call(wrap__DeleteSet__encode_v2, self)

DeleteSet$squash <- function() .Call(wrap__DeleteSet__squash, self)

DeleteSet$merge <- function(other) .Call(wrap__DeleteSet__merge, self, other)

#' @export
`$.DeleteSet` <- function (self, name) { func <- DeleteSet[[name]]; environment(func) <- environment(); func }

#' @export
`[[.DeleteSet` <- `$.DeleteSet`

Snapshot <- new.env(parent = emptyenv())

Snapshot$new <- function(state_map, delete_set) .Call(wrap__Snapshot__new, state_map, delete_set)

Snapshot$decode_v1 <- function(data) .Call(wrap__Snapshot__decode_v1, data)

Snapshot$decode_v2 <- function(data) .Call(wrap__Snapshot__decode_v2, data)

Snapshot$encode_v1 <- function() .Call(wrap__Snapshot__encode_v1, self)

Snapshot$encode_v2 <- function() .Call(wrap__Snapshot__encode_v2, self)

Snapshot$equal <- function(other) .Call(wrap__Snapshot__equal, self, other)

Snapshot$not_equal <- function(other) .Call(wrap__Snapshot__not_equal, self, other)

#' @export
`$.Snapshot` <- function (self, name) { func <- Snapshot[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Snapshot` <- `$.Snapshot`

TextRef <- new.env(parent = emptyenv())

TextRef$len <- function(transaction) .Call(wrap__TextRef__len, self, transaction)

TextRef$insert <- function(transaction, index, chunk) .Call(wrap__TextRef__insert, self, transaction, index, chunk)

TextRef$push <- function(transaction, chunk) .Call(wrap__TextRef__push, self, transaction, chunk)

TextRef$remove_range <- function(transaction, index, len) .Call(wrap__TextRef__remove_range, self, transaction, index, len)

TextRef$get_string <- function(transaction) .Call(wrap__TextRef__get_string, self, transaction)

TextRef$observe <- function(f, key) .Call(wrap__TextRef__observe, self, f, key)

TextRef$unobserve <- function(key) .Call(wrap__TextRef__unobserve, self, key)

#' @export
`$.TextRef` <- function (self, name) { func <- TextRef[[name]]; environment(func) <- environment(); func }

#' @export
`[[.TextRef` <- `$.TextRef`

TextEvent <- new.env(parent = emptyenv())

TextEvent$target <- function() .Call(wrap__TextEvent__target, self)

TextEvent$delta <- function(transaction) .Call(wrap__TextEvent__delta, self, transaction)

TextEvent$path <- function() .Call(wrap__TextEvent__path, self)

#' @export
`$.TextEvent` <- function (self, name) { func <- TextEvent[[name]]; environment(func) <- environment(); func }

#' @export
`[[.TextEvent` <- `$.TextEvent`

Update <- new.env(parent = emptyenv())

Update$decode_v1 <- function(data) .Call(wrap__Update__decode_v1, data)

Update$decode_v2 <- function(data) .Call(wrap__Update__decode_v2, data)

Update$new <- function() .Call(wrap__Update__new)

Update$is_empty <- function() .Call(wrap__Update__is_empty, self)

Update$extends <- function(state_vector) .Call(wrap__Update__extends, self, state_vector)

Update$encode_v1 <- function() .Call(wrap__Update__encode_v1, self)

Update$encode_v2 <- function() .Call(wrap__Update__encode_v2, self)

Update$state_vector <- function() .Call(wrap__Update__state_vector, self)

Update$state_vector_lower <- function() .Call(wrap__Update__state_vector_lower, self)

Update$to_string <- function() .Call(wrap__Update__to_string, self)

#' @export
`$.Update` <- function (self, name) { func <- Update[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Update` <- `$.Update`

Doc <- new.env(parent = emptyenv())

Doc$new <- function() .Call(wrap__Doc__new)

Doc$client_id <- function() .Call(wrap__Doc__client_id, self)

Doc$guid <- function() .Call(wrap__Doc__guid, self)

Doc$get_or_insert_text <- function(name) .Call(wrap__Doc__get_or_insert_text, self, name)

Doc$get_or_insert_map <- function(name) .Call(wrap__Doc__get_or_insert_map, self, name)

Doc$get_or_insert_array <- function(name) .Call(wrap__Doc__get_or_insert_array, self, name)

Doc$to_string <- function() .Call(wrap__Doc__to_string, self)

#' @export
`$.Doc` <- function (self, name) { func <- Doc[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Doc` <- `$.Doc`

# nolint end
