# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib yar, .registration = TRUE
NULL

# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_yar_wrappers", use_symbols = TRUE, package_name = "yar")

#' @usage NULL
#' @useDynLib yar, .registration = TRUE
NULL

Transaction <- new.env(parent = emptyenv())

Transaction$new <- function(doc) .Call(wrap__Transaction__new, doc)

Transaction$commit <- function() .Call(wrap__Transaction__commit, self)

Transaction$drop <- function() invisible(.Call(wrap__Transaction__drop, self))

#' @export
`$.Transaction` <- function (self, name) { func <- Transaction[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Transaction` <- `$.Transaction`

TextRef <- new.env(parent = emptyenv())

TextRef$insert <- function(transaction, index, chunk) invisible(.Call(wrap__TextRef__insert, self, transaction, index, chunk))

TextRef$get_string <- function(transaction) .Call(wrap__TextRef__get_string, self, transaction)

#' @export
`$.TextRef` <- function (self, name) { func <- TextRef[[name]]; environment(func) <- environment(); func }

#' @export
`[[.TextRef` <- `$.TextRef`

Doc <- new.env(parent = emptyenv())

Doc$new <- function() .Call(wrap__Doc__new)

Doc$client_id <- function() .Call(wrap__Doc__client_id, self)

Doc$guid <- function() .Call(wrap__Doc__guid, self)

Doc$get_or_insert_text <- function(name) .Call(wrap__Doc__get_or_insert_text, self, name)

#' @export
`$.Doc` <- function (self, name) { func <- Doc[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Doc` <- `$.Doc`

# nolint end
