name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Code checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.65.0
          cache: true
          environments: dev
      - name: Run checks and formatters through pre-commit
        run: pixi run pre-commit run --all-files

  test-unit:
    name: R tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-26-intel, macos-26, windows-2025]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.65.0
          cache: true
          environments: dev
      - name: Unit tests
        run: pixi run test-cargo
      - name: R integration tests
        run: pixi run test-r
